name: "Release Application"
on: push

env:
  EXPORT_NAME: "godot-cubemap-creator"

jobs:
  export:
    name: Export Platform ${{ matrix.platform }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [linux, mac, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-dotnet@v4
        name: "Setup Dotnet"
        with:
          dotnet-version: '8'

      - name: Restore Dependencies
        run: dotnet restore

      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          version: "4.3.0"
          use-dotnet: true
          include-templates: true

      - name: Setup Build
        run: |
          mkdir -p ~/.config/godot
          cat << EOF > ~/.config/godot/editor_settings-4.3.tres
          [gd_resource type="EditorSettings" format=3]
          [resource]
          export/windows/rcedit = "/opt/rcedit.exe"
          export/windows/wine = "/usr/bin/wine"
          EOF

      - name: Build
        run: |
          OS_TYPE=${{ matrix.platform }}
          if [[ "$OS_TYPE" == "linux" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.x86_64"
          elif [[ "$OS_TYPE" == "mac" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.zip"
          elif [[ "$OS_TYPE" == "windows" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.exe"
          else
            echo "Invalid OS type. Please specify 'linux', 'mac', or 'windows'."
            exit 1
          fi

          mkdir -v -p build/${{ matrix.platform }}
          godot --headless --verbose --export-release "${{ matrix.platform }}" "build/${{ matrix.platform }}/$EXPORT_FULL_NAME"

      - name: Set icon on Windows
        if: matrix.platform == 'windows'
        run: |
          wget https://raw.githubusercontent.com/pkowal1982/godoticon/refs/heads/master/CreateIcon.gd -O CreateIcon.gd
          wget https://raw.githubusercontent.com/pkowal1982/godoticon/refs/heads/master/ReplaceIcon.gd -O ReplaceIcon.gd
          godot --headless --verbose -s CreateIcon.gd icon.ico icon.png
          godot --headless --verbose -s ReplaceIcon.gd icon.ico ${EXPORT_NAME}.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: build/${{ matrix.platform }}
