name: "Release Application"
on: push

env:
  EXPORT_NAME: "godot-cubemap-creator"

jobs:
  export:
    name: Export Platform ${{ matrix.platform }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [linux, mac, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-dotnet@v4
        name: "Setup Dotnet"
        with:
          dotnet-version: '8'

      - name: Restore Dependencies
        run: dotnet restore

      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          version: "4.3.0"
          use-dotnet: true
          include-templates: true

      - name: Build
        run: |
          OS_TYPE=${{ matrix.platform }}
          if [[ "$OS_TYPE" == "linux" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.x86_64"
          elif [[ "$OS_TYPE" == "mac" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.zip"
          elif [[ "$OS_TYPE" == "windows" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.exe"
          else
            echo "Invalid OS type. Please specify 'linux', 'mac', or 'windows'."
            exit 1
          fi

          mkdir -v -p build/${{ matrix.platform }}
          godot --headless --verbose --export-release "${{ matrix.platform }}" "build/${{ matrix.platform }}/$EXPORT_FULL_NAME"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: build/${{ matrix.platform }}
