name: "Release Application"
on: push

env:
  EXPORT_NAME: "godot-cubemap-creator"

jobs:
  export:
    name: Export Platform ${{ matrix.platform }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [linux, mac, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-dotnet@v4
        name: "Setup Dotnet"
        with:
          dotnet-version: '8'

      - name: Restore Dependencies
        run: dotnet restore

      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          version: "4.3.0"
          use-dotnet: true
          include-templates: true

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt install --install-recommends winehq-stable

      - name: Install rcedit
        run: |
          wget https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe -O /opt/rcedit.exe

      - name: Setup Build
        run: |
          cat << EOF > ~/.config/godot/editor_settings-4.3.tres
          [gd_resource type="EditorSettings" format=3]
          [resource]
          export/windows/rcedit = "/opt/rcedit.exe"
          export/windows/wine = "wine"
          EOF

      - name: Build
        run: |
          OS_TYPE=${{ matrix.platform }}
          if [[ "$OS_TYPE" == "linux" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.x86_64"
          elif [[ "$OS_TYPE" == "mac" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.zip"
          elif [[ "$OS_TYPE" == "windows" ]]; then
            EXPORT_FULL_NAME="${EXPORT_NAME}.exe"
          else
            echo "Invalid OS type. Please specify 'linux', 'mac', or 'windows'."
            exit 1
          fi

          mkdir -v -p build/${{ matrix.platform }}
          godot --headless --verbose --export-release "${{ matrix.platform }}" "build/${{ matrix.platform }}/$EXPORT_FULL_NAME"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: build/${{ matrix.platform }}
